### ISSUE TITLE
Version Problem 

### ISSUE THREAD

**Issue by HariBabu2535** [ExplorerUK/IG-Hide-Interactive-Grid-Settings-Plugin#1]
Hi,
When I am installing the plugin in oracle apex . I am getting the error like version compatibility because my oracle apex account version is 18 and the plugin version is 19 which is latest can you help me on this.

**Comment by explorerMMulvaney** [comment]
Hi HariBabu2535,
The plugin was created for APEX 19.2 as the lowest version.
You can try to downgrade the plugin by installing the plugin on apex.oracle.com - once installed, you can copy the components/settings/source files from the plugin to a new plugin in your APEX 18 instance.
There's no guarantees this would work; for example the plugin might be using APIs which didn't exist in 18 or the markup may be different
let me know if you have any success
Matt
